# Generated by Django 4.2 on 2023-08-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_contact1'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=100)),
                ('button_text', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='settings/')),
                ('site_name', models.CharField(max_length=100)),
            ],
        ),
    ]
