# Generated by Django 4.2 on 2023-08-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_innerpage_delete_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='innerpage',
            name='page_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
