# Generated by Django 4.2 on 2023-08-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_innerpage_page_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menuStyle/')),
                ('menu_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='websitesettings',
            old_name='subtitle',
            new_name='innerPage_Subtitle',
        ),
        migrations.RenameField(
            model_name='websitesettings',
            old_name='title',
            new_name='main_title',
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='innerPage_title',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='main_subtitle',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='innerpage',
            name='page_type',
            field=models.CharField(default=True, max_length=50, null=True),
        ),
    ]
