# Generated by Django 4.2 on 2023-08-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_menustyle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innerpage',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='innerpage',
            name='title',
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='device_support_image',
            field=models.ImageField(null=True, upload_to='devices/'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='device_support_subtitle',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='device_support_title',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='layoutPage_button_text',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='layoutPage_image1',
            field=models.ImageField(default=True, upload_to='layImage1/'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='layoutPage_image2',
            field=models.ImageField(default=True, upload_to='layImage2/'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='layoutPage_subtitle',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='layoutPage_title',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='innerPage_Subtitle',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
