# Generated by Django 4.2 on 2023-08-05 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_innerpage_subtitle_remove_innerpage_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitesettings',
            name='image',
        ),
    ]
