# Generated by Django 4.2 on 2023-08-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_websitesettings_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='device_support_image',
            field=models.ImageField(blank=True, null=True, upload_to='devices/'),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='device_support_subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='device_support_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='layoutPage_button_text',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='layoutPage_image1',
            field=models.ImageField(blank=True, null=True, upload_to='layImage1/'),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='layoutPage_image2',
            field=models.ImageField(blank=True, null=True, upload_to='layImage2/'),
        ),
    ]
