# Generated by Django 4.2 on 2023-08-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_websitesettings_device_support_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='innerPage_Subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='innerPage_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='layoutPage_subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='layoutPage_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
