# Generated by Django 4.2 on 2023-08-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_websitesettings_innerpage_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='file_path',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
