# Generated by Django 4.2 on 2023-08-08 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_websitesettings_layoutpage_button_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('id_or_href', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_display', models.BooleanField(default=True)),
                ('is_dropdown_menu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Submenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submenu_type', models.CharField(max_length=20)),
                ('id_or_href', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(verbose_name=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.menu')),
            ],
        ),
    ]
