# Generated by Django 4.2 on 2023-08-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_menu_submenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='is_display',
        ),
    ]
