# Generated by Django 4.2 on 2023-08-08 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_remove_menu_is_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='is_dropdown_menu',
        ),
    ]
