# Generated by Django 4.2 on 2023-08-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_remove_menu_is_dropdown_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='innerpage',
            name='file_path',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
