# Generated by Django 4.2 on 2023-08-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_innerpage_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='file_path',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
