# Generated by Django 4.2 on 2023-08-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_showcase_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=200)),
                ('image1', models.ImageField(upload_to='layImage1/')),
                ('image2', models.ImageField(upload_to='layImage2/')),
                ('button_text', models.CharField(max_length=10)),
                ('file_path', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='websitesettings',
            name='layoutPage_button_text',
        ),
        migrations.RemoveField(
            model_name='websitesettings',
            name='layoutPage_image1',
        ),
        migrations.RemoveField(
            model_name='websitesettings',
            name='layoutPage_image2',
        ),
        migrations.RemoveField(
            model_name='websitesettings',
            name='layoutPage_subtitle',
        ),
        migrations.RemoveField(
            model_name='websitesettings',
            name='layoutPage_title',
        ),
    ]
