# Generated by Django 4.2 on 2023-08-09 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_layoutpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='file_path',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DropdownMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_type', models.CharField(max_length=20)),
                ('id_or_href', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(verbose_name=True)),
                ('file_path', models.CharField(max_length=50)),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.submenu')),
            ],
        ),
    ]
