# Generated by Django 4.2 on 2023-08-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_remove_dropdownmenu_id_or_href_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='type',
            new_name='menu_type',
        ),
    ]
