# Generated by Django 4.2 on 2023-08-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_rename_menu_type_dropdownmenu_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menustyle',
            name='file_path',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menustyle',
            name='image',
            field=models.ImageField(upload_to='menuStyles/'),
        ),
    ]
