# Generated by Django 4.2 on 2023-08-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_menustyle_file_path_alter_menustyle_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact1',
            old_name='budget',
            new_name='your_budget',
        ),
    ]
