# Generated by Django 4.2 on 2023-08-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_rename_budget_contact1_your_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('project_type', models.CharField(max_length=50)),
                ('budget', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='contact1',
            old_name='your_budget',
            new_name='budget',
        ),
    ]
